Boss class revision.
DSusol/Don_Kabani pull request #3
Opened 2022-01-09 16:49 UTC by DSusol

BOSS CLASS REVISION:

- Boss class is revised to be a BossFactory class.

- Parant class Attributable is created. It defines attributes for bosses, DonKabani (not updated yet) and Shmot (not updated yet).
Child classes: Roshan, Bear, Fox (bosses) + DonKabany (not updated yet) + Shmot (not updated yet).

If pull requires is approved, then DonKabany and Shmot classes will be revised accordingly.

2022-01-09 17:43 UTC, tkachenkoas requested changes

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Bear.java
> +        final int extraAttackPhysical = 8;
зачем объявлять переменную, если ты её используешь один раз в почти следующей строчке?

сделай её прайвет-стати-файнал

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Bear.java
> +    public void showWelcomeStory() {
возвращай строку вместо вывода в консоль

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/supplemental/Constants.java
> +    public static final double HARD_SCALE_FACTOR = 1.1;
эти три скейл факторы должны быть enum'ом - посмотри видосы о том, что это такое

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/supplemental/Methods.java
> +public final class Methods {
вообще, подобные вспомогательные классы называют **Utils (StringUtils, RandomUtils, DonKabaniUtils...)

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/locations/Fight.java
> +                int bossDamageDeal = (int) Methods.randPercent(bossDamage
кастинг не нужен. у тебя randPercent уже возвращает целое число

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/locations/Fight.java
> +        String dmgType = Methods.getInput(quesDmg,
а почему такой перенос строки короткий? чекстайл ругается?

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Roshan.java
> +    private final String attackType;
attackType тоже должен быть enum'ом, а не стрингой

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Roshan.java
> +        final int extraHealthPoints = 100;
вынеси эти числа константами, а не "определил в одной строке, использовал в соседней"

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/DonKabani.java
> +public final class DonKabani {
а што, донкабани у нас не экстендит и не имплементит ничего?

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Attributable.java
> +        if (!automaticallyGenerated) {
вообще, boolean параметры в методах - это в 95% случаев зло.

всей логикой создания заведует фактори - она должна обработать всю логику и передать объектам в конктрукторы конкретные числа, а на булеан флаги, чтобы абстрактный класс что-то там умно решал для себя 20 раз =)

на практике это означает - что тебе нужны два разных метода (create() + createAndAddAtrributes() ), а в случае с конструтором - у тебя должен быть конструктор DonKabani(Attributable bonusAttributes)

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Attributable.java
> +public abstract class Attributable {
вообще, *Able - это паттерн имени интерфейса, а не абстрактного класса

абстрактные классы обычно называют Abstract** -> AbstractAttributable

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Attributable.java
> +    private void scaleAttributes(final double scaleFactor) {
вынеси всю эту логику в фактори. не держи никакой общей сложной логики в абстрактном классе (потому что ты делаешь его слишком конкретным)

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Bear.java
> +        if (scaleFactor == Constants.HARD_SCALE_FACTOR) {
ещё как вариант можно сделать BearFactory и вынеси всю медведеориентированную создающую логику туда (аналогично - FoxFactory / RoshanFactory)

То есть, у тебя будет BossFactory, а у неё будут три "раба" - МедведеФабрика, ЛисоФабрика и РошаноФабрика
тогда мы возможно вернемся к исходному варианту, где будет один тупой класс Boss, которому фактори будут передавать набор аттрибутов

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Bear.java
> +        this.attackType = "physical";
правильно ли я понимаю, что если тип атаки физическая - то всякие поля "магическая атака" не имеют смысла?

может быть, нужно как в варкрафте у юнита сделать "тип атаки", "тип защиты" и "урон", а не десять полей на каждый тип? а что будет, когда новый тип появится - в сто классов юнитов будешь дописывать сто новых полей, половина из которых будет нулями? :)

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Bear.java
> +        System.out.println("The game is over.");
мне кажется странным, что медведь пишет о том, что игра закончена и что он кого-то разорвал. это ответственность класса, который управляет боем / общим повествованием

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/BossFactory.java
> +        while (!roshanIsCreated || !bearIsCreated || !foxIsCreated) {
а зачем вообще эти рандомы? просто создать по одной лисе, мишке и рошану никак? :)

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/BossFactory.java
> +        this.bossList.remove(0);
погугли интерфейс Queue и его простейшую имплементацию - LinkedList

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/BossFactory.java
> +        while (!roshanIsCreated || !bearIsCreated || !foxIsCreated) {
если тебе нужен рандомный порядок боссов - есть https://www.baeldung.com/java-shuffle-collection

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/DonKabani.java
> +public final class DonKabani {
игровой персонаж должен быть тоже имплементацией интерфейса "БоевойЮнит" - он на высоком уровне ничем не должен отличаться от медведей или лисов.

и в теории, у тебя Fight должен быть между БоевойЮнит и БоевойЮнит - чтобы Лиса и Медведь тоже могли драться между собой по тем же правилам

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/DonKabani.java
>      public int getHp() {
так же как и у Лисы/Медведя, должен быть метод getHealth - но разница получается в том, что у ДонаКабани он рассчитываемый через baseHp + bonusesFromitems...

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Fox.java
> +    private final String name;
если три класса получились одинаковые по полям, но разные по конструкторам - это значит, что у тебя один класс, но три разные логики создания его (которые должны быть обработаны фабриками)

привыкай сразу, что логика в конструкторах - это 💩

2022-01-09 17:43 UTC, tkachenkoas commented on src/main/java/game/character/Attributable.java
> +    public void addSpeed(final int addedSpeed) {
если все эти add** методы предназначен только для имплементаций (для удобства) - то делай их protected

2022-01-15 23:31 UTC, DSusol commented on src/main/java/game/character/Attributable.java
> +    private void convertDefaultsToRandom() {
> это логика создания, а не абстрактного класса - засунь её в фактори

Уточню. Эта логика будет одинаковой для всех сабклассов. Скажем, ребёнок при рождении может обладать такими рандомными характеристиками, как рост, вес, м или ж, цвет глаз и тд. Также и тут - это часть инициализации полей, которая делает полученный объект уникальным по этим полям. 

Всё равно эту часть конструктора стоит отправить в фабрику?

2022-01-16 00:44 UTC, DSusol commented on src/main/java/game/character/Attributable.java
> +    public int getAttackPhysical() {
> погугли lombok @getter - половина всех твоих геттеров уйдет прочь

потестил lombok @Getter на тестовом классе - всё ок
в проекте фейлится:

public final class Bear extends Character implements Fighting { .. }
1) Поле getHealthPoints задано в классе Character, требование геттера в интерфейсе Fighting
2) в классе Character убиваю геттер, Идея выделяет эту строку, тк требования интерфейса не выполнены
3) добавляю аннотацию
4) Идея убирает выделение, всё вроде ок, запускаю..
5) E:\Programming\Lessons\Java\Anton\Don_Kabani\src\main\java\game\character\Bear.java:5: error: Bear is not abstract and does not override abstract method getHealthPoints() in Fighting

2022-01-16 15:46 UTC, DSusol commented on src/main/java/game/supplemental/Constants.java
> +    public static final double HARD_SCALE_FACTOR = 1.1;
внедрил, но чёт выглядит не очень, сегодня обсудим

2022-01-16 15:55 UTC, DSusol commented on src/main/java/game/locations/Fight.java
> +        String dmgType = Methods.getInput(quesDmg,
Да, плюс много вложенных циклов, что отодвигает строку вправо. Как дойду до класса Fight, то переделаю на дополнительные методы. Пока просто чтобы чеклист обойти.

2022-01-16 15:58 UTC, DSusol commented on src/main/java/game/character/Roshan.java
> +    private final String attackType;
ок
я правильно понимаю, что это делается с той целью, чтобы наложить требования на это поле (выбор из 2-3 вариантов), чтобы эта логика явно отображалась в коде

2022-01-16 16:15 UTC, DSusol commented on src/main/java/game/character/DonKabani.java
> +public final class DonKabani {
да, верно, я в этом пул реквесте делаю только фабрику боссов, потом поменяю остальной код

2022-01-16 17:13 UTC, DSusol commented on src/main/java/game/character/Attributable.java
> +        if (!automaticallyGenerated) {
создал промежуточный абстрактный класс Bosses и перенёс боссовую логику туда

2022-01-16 17:17 UTC, DSusol commented on src/main/java/game/character/Bear.java
> +        if (scaleFactor == Constants.HARD_SCALE_FACTOR) {
внедрил все предыдущие комменты и тут на, всё переделай))
давай обговорим

2022-01-16 17:18 UTC, DSusol commented on src/main/java/game/character/Bear.java
> +        this.attackType = "physical";
можно, но из 8 параметров только один не будет использоваться в бою
это изменение, опять же, убьёт всю существующую логику наследования
стоит заморачиваться?)

2022-01-16 17:23 UTC, DSusol commented on src/main/java/game/character/Bear.java
> +        System.out.println("The game is over.");
Давай я исправлю этот метод на "Медвед рычит и хохочит на весь лес?").
Класс боя и вызывает этот метод. Или нужно наплодить там условия по боссам и вывести соответствующий конец напрямую текстом?

2022-01-16 17:26 UTC, DSusol commented on src/main/java/game/character/BossFactory.java
> +        while (!roshanIsCreated || !bearIsCreated || !foxIsCreated) {
Мне нужен рандомный порядок боссов с увеличивающейся сложностью (скеил фактор), и фактор используется в момент создания объекта босса.

2022-01-16 17:34 UTC, DSusol commented on src/main/java/game/character/BossFactory.java
> +        this.bossList.remove(0);
удобненько

2022-01-16 17:34 UTC, DSusol commented on src/main/java/game/character/DonKabani.java
>      public int getHp() {
Дона Кабани я позже поправлю

2022-01-16 17:37 UTC, DSusol commented on src/main/java/game/character/Fox.java
> +    private final String name;
ладно, сдаюсь :)

2022-01-23 16:55 UTC, tkachenkoas commented on build.gradle
> +sourceCompatibility = JavaVersion.VERSION_16
11, please

2022-01-23 16:55 UTC, tkachenkoas commented on src/main/java/game/Engine.java
> +    public Engine() {
не надо прописывать пустой паблик конструктор - его компилятор по дефолту делает

2022-01-23 16:56 UTC, tkachenkoas commented on src/main/java/game/Engine.java
> +        BossManager bosses = new BossManager();
нейминг -> bossManager, а не bosses

2022-01-23 16:57 UTC, tkachenkoas commented on src/main/java/game/character/Character.java
> +    private String name = null;
null и так дефолтное значение для поля, на надо его прописывать явно

2022-01-23 16:57 UTC, tkachenkoas commented on src/main/java/game/character/Character.java
> +@Setter
@Data очень хорошая аннотация

2022-01-23 16:58 UTC, tkachenkoas commented on src/main/java/game/character/Character.java
> +    public String showAttributes() {
getAttributesString()

2022-01-23 16:58 UTC, tkachenkoas commented on src/main/java/game/character/Character.java
> +        return "\tHealth points: \t\t" + this.healthPoints + "\n"
изучи класс MessageFormat

2022-01-23 16:58 UTC, tkachenkoas commented on src/main/java/game/character/Character.java
> +                + "\tSpeed: \t\t\t\t" + this.speed;
и выкинь все эти табы =)

2022-01-23 16:59 UTC, tkachenkoas commented on src/main/java/game/character/Fighting.java
> +    int getAttackPhysical();
AttackType getAttackType() как бы подразумевает что у тебя только один тип атаки,а не два и не три, которые отдельно можно спросить

2022-01-23 17:00 UTC, tkachenkoas commented on src/main/java/game/character/Character.java
> +public abstract class Character {
ну и абстрактные классы я вообще не люблю. без него никак? :)

2022-01-23 17:01 UTC, tkachenkoas commented on src/main/java/game/character/Character.java
> +public abstract class Character {
этот класс у тебя implements Fighting или нет? :)

2022-01-23 17:02 UTC, tkachenkoas commented on src/main/java/game/character/boss/BearFactory.java
> +    static Boss create(final Boss boss) {
plz no static :)
и почему у тебя фактори принимает какого-то босса, а не с нуля создает?

2022-01-23 17:04 UTC, tkachenkoas commented on src/main/java/game/character/boss/BearFactory.java
> +final class BearFactory {
BearFactory мне кажется должна имплементить какой-то 
interface BossFactoryDelegate {
    BossType applicableForRequestedBossType();
    Boss createBoss();
}

2022-01-23 17:05 UTC, tkachenkoas commented on src/main/java/game/character/boss/Boss.java
> +    private final List<String> skills;  // to be included later
ну точно не стрингами это будет :) но пока - ок...

2022-01-23 17:06 UTC, tkachenkoas commented on src/main/java/game/character/boss/BearFactory.java
> +        boss.setCriticalChance(boss.getCriticalChance()
один общий класс Constants на все юскейсы - очень плохая идея.

BEAR_EXTRA_ATTACK_PHYSICAL используется только в этой фабрике - так что пусть только к ней и относится

2022-01-23 17:07 UTC, tkachenkoas commented on src/main/java/game/character/boss/BearFactory.java
> +    static Boss create(final Boss boss) {
кстати, статические методы и интерфейсы несовместимы, так что статики вдвойне нафиг не нужны

2022-01-23 17:08 UTC, tkachenkoas commented on src/main/java/game/character/Character.java
> +    private int defencePhysical = Constants.DEFAULT_DEFENCE_PHYSICAL;
хм, то есть я так понял, что абстрактный класс тебе надо только чтобы задать базовые значения, которые потом будет увеличиваться в зависимости от типа босса?

2022-01-23 17:10 UTC, tkachenkoas commented on src/main/java/game/character/boss/BossFactory.java
> +    static LinkedList<Boss> createBossList() {
ноу статик методз плиз!

new BossFactory() и алга

2022-01-23 17:10 UTC, tkachenkoas commented on src/main/java/game/character/boss/BossFactory.java
> +        LinkedList<Boss> list = new LinkedList<>();
вай ду ю нид линкедлист?

2022-01-23 17:12 UTC, tkachenkoas commented on src/main/java/game/character/boss/BossFactory.java
> +        for (int iAttribute = 1; iAttribute <= 20; iAttribute++) {
так... это типа рандомные бонусы накидываешь?.. мне это усложнение не нравится, но ок, пусть пока поживет :)

2022-01-23 17:13 UTC, tkachenkoas commented on src/main/java/game/character/boss/BossManager.java
> +        if (String.valueOf(BossesList.ROSHAN).equals(boss.getName())) {
у енумов есть метод .name(), который тебе вернет "ROSHAN"

2022-01-23 17:15 UTC, tkachenkoas commented on src/main/java/game/character/boss/RoshanFactory.java
> +        switch (difficulty) {
дошел уже до мап? это ещё вот так можно сделать

Map.of(
   Difficulty.NONE, "Tiny",
   Difficulty.HARD, "Huge"
).get(difficulty)

2022-01-23 17:16 UTC, tkachenkoas commented on src/main/java/game/locations/DremuchiyForest.java
> +import game.character.don_kabani.DonKabani;
пакаджи с андерскором это прям хайлевел :)

2022-01-23 17:17 UTC, tkachenkoas commented on src/main/java/game/locations/DremuchiyForest.java
> +        System.out.println(StoryTeller.tellWelcomeStory(boss));
сделай поле в классе: StoryTeller teller = new StoryTeller()

teller.tellWelcomeStory(boss)

2022-01-23 17:17 UTC, tkachenkoas commented on src/main/java/game/locations/DremuchiyForest.java
> +        System.out.println(StoryTeller.tellWelcomeStory(boss));
ну и как бы сторителлер сам в состоянии вывести в консоль, судя по его названию :)

2022-01-23 17:19 UTC, tkachenkoas commented on src/main/java/game/locations/DremuchiyForest.java
>          Fight.start(kabani, boss, this.difficulty);
если fight у тебя будет возвращать какой-то результат, то это будет полезно управляющему компоненту :)

2022-01-23 17:20 UTC, tkachenkoas commented on src/main/java/game/locations/StoryTeller.java
> +            return "\n\n *******************************************\n"
MessageFormat

2022-01-23 17:23 UTC, tkachenkoas commented on src/main/java/game/locations/StoryTeller.java
> +        if (boss.getName().contains(
BossesList.ROSHAN.name().toLowerCase()

2022-01-23 17:24 UTC, tkachenkoas commented on src/main/java/game/locations/StoryTeller.java
> +            return "\n\n *******************************************\n"
ну шо, перейдём к хардконому хардкору? :) как насчет того, чтобы положить эти тексты в файлики и прочитать их оттуда? :)

2022-01-23 17:25 UTC, tkachenkoas commented on src/main/java/game/supplemental/BossesList.java
> +public enum BossesList {
BossType более корректное имя

2022-01-23 17:26 UTC, tkachenkoas commented on src/main/java/game/locations/StoryTeller.java
> +            return "\n\n *******************************************\n"
но тут я прям рекомендую сделать юнит-тест, чтобы можно было прогнать один только класс, а не дергать каждый раз все приложение

2022-01-23 17:29 UTC, tkachenkoas commented on src/main/java/game/character/boss/BossManager.java
> +    public Boss getBoss() {
все паблик методы должны быть выше приватных методов

2022-01-23 17:29 UTC, tkachenkoas commented on src/main/java/game/character/boss/BossManager.java
> +    private void adjustBossDifficulty() {
ты готов юнит-тесты писать уже, а? :) у меня для тебя мильён идей о том, как всё отрефакторить покрасивше

2022-01-23 17:32 UTC, tkachenkoas commented on src/main/java/game/character/Character.java
> +    private int defencePhysical = Constants.DEFAULT_DEFENCE_PHYSICAL;
в общем, я бы вместо общих дефолтных значений и разницы в каждой фабрике бы определял начальные значения для каждого пацана

а то как-то тупо - ты сделал базу 100 для всех, а потом сложность растет у тебя будет босс ЗлойСердитыйЧерныйДракон у которого будет бонусХп в 1900 - и эти 100, которые ты изначально под мишку с лисичкой придумывал, вообще нафиг не нужны ему

2022-01-23 17:35 UTC, tkachenkoas commented on src/main/java/game/character/boss/BearFactory.java
> +    static String getBearType(Difficulty difficulty) {
на уровне интерфейса этот метод будет называться "getBossDifficultyLabel"

2022-01-23 17:36 UTC, tkachenkoas requested changes
я пока не могу сказать, что я рад :)
но важно также закончить с текущим скоупом изменений и не начинать новые, а то я как чучка - "что вижу, о том и пою" :)

2022-01-29 17:43 UTC, tkachenkoas requested changes
хорошо. я отстану пока от всех классов-интерфейсов, но сделай чтение из файлов красивее (а также положи файлы в /resources

![image](https://user-images.githubusercontent.com/30129586/151671489-f9e50f82-37a5-4222-98c3-d58e9b8be07e.png)

2022-01-29 17:43 UTC, tkachenkoas commented on src/main/java/game/locations/Stories.txt
> +ROSHAN welcome story
сделай папку с 6 файлами:
roshan-welcome.txt
roshan-end.txt
...

и читай файл целиком

2022-01-29 17:43 UTC, tkachenkoas commented on src/main/java/game/locations/Stories.txt
> +ROSHAN welcome story
и все текстовые ресурсы должны быть в src/main/resources

2022-01-29 17:43 UTC, tkachenkoas commented on src/main/java/game/locations/StoryTeller.java
> +    private String readFromFile(String bossType, String bossName, String storyType) {
https://stackoverflow.com/questions/6068197/utils-to-read-resource-text-file-to-string-java

yegor256 has found a nice solution using Apache Commons IO:
import org.apache.commons.io.IOUtils;
String text = IOUtils.toString(this.getClass().getResourceAsStream("foo.xml"), "UTF-8");

очень не рекомендую руками писать код, который читает или пишет в файлы :)
там мутотень с try-catch-finally всегда и с закрытием ресурсов... уже написан миллион библиотек для этого

есть вроде даже вариант и со стандартными jdk классами типа Files, но они подлиннее

2022-02-20 16:26 UTC, closed without merging